apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "questions-db"
  namespace: "default"
  labels:
    app: "questions-db"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "questions-db"
  template:
    spec:
      containers:
      - name: "postgres"
        image: 'postgres:9.6'
        env:
        - name: "POSTGRES_DB"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_DB"
              name: "questions-db-configmap"
        - name: "POSTGRES_USER"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_USER"
              name: "questions-db-configmap"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_PASSWORD"
              name: "questions-db-configmap"
        ports:
          - containerPort: 5432
            name: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: questions-db-service
spec:
  ports:
    - port: 5432
  selector:
    app: questions-db

