version: "3"
services:
  postgresql:
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev
  solution-tester-worker-app:
    image: 'solution-tester-worker-app'
    ports:
      - 5003:5003