version: "3"
services:
  gitea:
    image: gitea/gitea:1.15.3
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
  postgresql:
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev
  repo-listener:
    image: 'repo-listener'
    ports:
      - 5000:5000
    depends_on:
      - postgresql
    environment:
      - DB_URI=postgresql://dev:dev@postgresql:5432/dev
  worker-app:
    image: 'worker-app'
    ports:
      - 5001:5001
    depends_on:
      - postgresql
    environment:
      - DB_URI=postgresql://dev:dev@postgresql:5432/dev
      - TMP_DIR=/tmp-dir/
      - REPO_BASE_URL=gitea
  worker-monitoring-app:
    image: 'worker-monitoring-app'
    ports:
      - 5002:5002
    depends_on:
      - postgresql
    environment:
      - DB_URI=postgresql://dev:dev@postgresql:5432/dev
