version: "3"
services:
  gitea:
    image: gitea/gitea:1.15.3
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
  postgresql:
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev
  repo-listener:
    image: 'repo-listener'
    ports:
      - 5000:5000
    depends_on:
      - postgresql
    environment:
      - DB_URI=postgresql://dev:dev@postgresql:5432/dev
  worker-app:
    image: 'worker-app'
    ports:
      - 5001:5001
    depends_on:
      - postgresql
    environment:
      - DB_URI=postgresql://dev:dev@postgresql:5432/dev
      - TMP_DIR=/tmp-dir/
      - REPO_BASE_URL=gitea
      - MINIO_HOST=object-storage:9000
  worker-monitoring-app:
    image: 'worker-monitoring-app'
    ports:
      - 5002:5002
    depends_on:
      - postgresql
    environment:
      - DB_URI=postgresql://dev:dev@postgresql:5432/dev
  object-storage:
    image: 'minio/minio'
    command: 'server /data --console-address ":9001"'
    expose:
      - 9000
      - 9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
  client-app:
    image: 'client-app'
    ports:
      - 80:80
    depends_on:
      - gitea
    environment:
      - MINIO_HOST=object-storage:9000