apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "gitea-repository"
  namespace: "default"
  labels:
    app: "gitea-repository"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "gitea-repository"
  template:
    metadata:
      labels:
        app: "gitea-repository"
    spec:
      containers:
        - name: "gitea-repository"
          image: "gitea/gitea:1.15.3"
          imagePullPolicy: Always
          env:
            - name: "USER_UID"
              value: "1000"
            - name: "USER_GID"
              value: "1000"

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gitea-repository-service"
  namespace: "default"
  labels:
    app: "gitea-repository-service"
spec:
  ports:
    - protocol: "TCP"
      name: ui
      port: 3000
      targetPort: 3000
    - protocol: "TCP"
      name: api
      port: 222
      targetPort: 22
  selector:
    app: "gitea-repository"
  type: "LoadBalancer"
  loadBalancerIP: ""
